# Generated by Django 5.0.7 on 2025-09-05 10:11

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='customer_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Trẻ em (<6)'), (2, 'HSSV (<23)'), (3, 'Người lớn'), (4, 'Người già (>60)')], help_text='Nếu bỏ trống sẽ tự gợi ý theo ngày sinh + is_student', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Đánh dấu nếu là học sinh/sinh viên thực sự'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['customer_type'], name='accounts_us_custome_e47f5a_idx'),
        ),
    ]
