# Generated by Django 5.0.7 on 2025-09-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_customer_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='user_dob_not_in_future',
        ),
    ]
