# Generated by Django 5.0.7 on 2025-08-18 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0006_alter_place_phone_alter_place_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('total_cost', models.PositiveIntegerField(default=0)),
                ('total_duration_s', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('share_code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_start', models.DateTimeField()),
                ('visit_end', models.DateTimeField()),
                ('transport_mode', models.CharField(choices=[('walk', 'Walk'), ('bike', 'Bike'), ('taxi', 'Taxi')], default='walk', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='itineraries.itinerary')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
