# Generated by Django 5.0.7 on 2025-08-23 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
        ('places', '0006_alter_place_phone_alter_place_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='leg_cost_vnd',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='leg_distance_m',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='leg_duration_s',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='ticket_cost_vnd',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='share_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.place'),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='transport_mode',
            field=models.CharField(default='walk', max_length=16),
        ),
    ]
