# Generated by Django 5.0.7 on 2025-09-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_itineraryitem_leg_cost_vnd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='visit_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='visit_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
