# Generated by Django 5.0.7 on 2025-09-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_alter_itineraryitem_visit_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='leg_cost_vnd',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='leg_distance_m',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='leg_duration_s',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='ticket_cost_vnd',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
