# Generated by Django 5.0.7 on 2025-09-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_alter_itineraryitem_leg_cost_vnd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryitem',
            name='visit_end',
        ),
        migrations.RemoveField(
            model_name='itineraryitem',
            name='visit_start',
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='leg_cost_vnd',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='leg_distance_m',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='leg_duration_s',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='ticket_cost_vnd',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
