# Generated by Django 5.0.7 on 2025-09-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_remove_itineraryitem_visit_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itineraryitem',
            options={'ordering': ('visit_date', 'order', 'id')},
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='visit_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
