# Generated by Django 5.0.7 on 2025-09-16 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_alter_itineraryitem_options_itineraryitem_visit_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount_vnd', models.PositiveBigIntegerField(default=0)),
                ('contributed_amount_vnd', models.PositiveBigIntegerField(default=0)),
                ('spent_amount_vnd', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund', to='itineraries.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='FundInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('amount_vnd', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('CANCELED', 'Canceled')], default='UNPAID', max_length=10)),
                ('pay_source', models.CharField(blank=True, choices=[('FUND', 'Fund'), ('VNPAY', 'Vnpay')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='itineraries.itineraryfund')),
            ],
        ),
        migrations.CreateModel(
            name='FundContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_vnd', models.PositiveBigIntegerField()),
                ('purpose', models.CharField(choices=[('TOPUP', 'Topup'), ('INVOICE', 'Invoice')], default='TOPUP', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('vnp_txn_ref', models.CharField(db_index=True, max_length=64, unique=True)),
                ('vnp_bank_code', models.CharField(blank=True, max_length=32, null=True)),
                ('vnp_order_info', models.CharField(blank=True, max_length=255, null=True)),
                ('vnp_transaction_no', models.CharField(blank=True, max_length=64, null=True)),
                ('vnp_pay_date', models.CharField(blank=True, max_length=20, null=True)),
                ('vnp_secure_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('vnp_raw', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_contributions', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='itineraries.fundinvoice')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='itineraries.itineraryfund')),
            ],
        ),
        migrations.CreateModel(
            name='FundPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_vnd', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='itineraries.fundinvoice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='itineraries.itineraryfund')),
            ],
            options={
                'indexes': [models.Index(fields=['fund', 'created_at'], name='itineraries_fund_id_128e76_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fundinvoice',
            index=models.Index(fields=['fund', 'status'], name='itineraries_fund_id_a81d61_idx'),
        ),
        migrations.AddIndex(
            model_name='fundinvoice',
            index=models.Index(fields=['created_at'], name='itineraries_created_903875_idx'),
        ),
        migrations.AddIndex(
            model_name='fundcontribution',
            index=models.Index(fields=['fund', 'status'], name='itineraries_fund_id_7b313a_idx'),
        ),
        migrations.AddIndex(
            model_name='fundcontribution',
            index=models.Index(fields=['purpose', 'status'], name='itineraries_purpose_64890c_idx'),
        ),
        migrations.AddIndex(
            model_name='fundcontribution',
            index=models.Index(fields=['created_at'], name='itineraries_created_c42059_idx'),
        ),
    ]
