# Generated by Django 5.0.7 on 2025-08-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('culture', 'Văn hoá'), ('history', 'Lịch sử'), ('museum', 'Bảo tàng'), ('park', 'Công viên'), ('market', 'Chợ'), ('religion', 'Tôn giáo'), ('landmark', 'Công trình'), ('other', 'Khác')], db_index=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('rating_avg', models.FloatField(default=0)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='places_plac_categor_0dcb38_idx'), models.Index(fields=['name'], name='places_plac_name_39c762_idx')],
            },
        ),
    ]
