# Generated by Django 5.0.7 on 2025-08-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='slug',
        ),
    ]
