# Generated by Django 5.0.7 on 2025-08-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_category_alter_place_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
