# Generated by Django 5.0.7 on 2025-08-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_image_public_id_place_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating_avg',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
