# Generated by Django 5.0.7 on 2025-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_phone_alter_place_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='ticket_price',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
