# Generated by Django 5.0.7 on 2025-09-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_place_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rating_avg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='reviews_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
