# Generated by Django 5.0.7 on 2025-09-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_options_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_place_i_3da8a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_user_id_a65d48_idx',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
