# Generated by Django 5.0.7 on 2025-09-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='CUL', max_length=50),
            preserve_default=False,
        ),
    ]
