# Generated by Django 5.0.7 on 2025-09-13 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='postlike',
            name='posts_postl_user_id_8dc185_idx',
        ),
        migrations.RemoveIndex(
            model_name='postlike',
            name='posts_postl_post_id_d568f5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_rows', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', 'user'], name='posts_postl_post_id_af824a_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['-created_at'], name='posts_postl_created_8fd2d0_idx'),
        ),
    ]
