# Generated by Django 5.0.7 on 2025-09-13 00:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_postlike_posts_postl_user_id_8dc185_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['-created_at'], name='posts_comme_created_6f9992_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['-created_at'], name='posts_react_created_ca678a_idx'),
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
